import type { FunctionDef } from './types'

/**
 * MySQL 内置函数清单。
 * minVersion 为主版本号，如 "8" 表示 MySQL 8.0+ 可用。
 * 参考：https://dev.mysql.com/doc/refman/en/functions.html
 */
export const MYSQL_FUNCTIONS: FunctionDef[] = [
  // ===== 聚合函数 =====
  {
    name: 'COUNT',
    signature: 'COUNT(expr)',
    description: '统计行数。COUNT(*) 含 NULL，COUNT(col) 忽略 NULL。',
    category: 'aggregate',
    insertText: 'COUNT(${1:*})',
  },
  {
    name: 'SUM',
    signature: 'SUM(expr)',
    description: '求和，忽略 NULL。',
    category: 'aggregate',
    insertText: 'SUM(${1:column})',
  },
  {
    name: 'AVG',
    signature: 'AVG(expr)',
    description: '计算平均值，忽略 NULL。',
    category: 'aggregate',
    insertText: 'AVG(${1:column})',
  },
  {
    name: 'MIN',
    signature: 'MIN(expr)',
    description: '求最小值。',
    category: 'aggregate',
    insertText: 'MIN(${1:column})',
  },
  {
    name: 'MAX',
    signature: 'MAX(expr)',
    description: '求最大值。',
    category: 'aggregate',
    insertText: 'MAX(${1:column})',
  },
  {
    name: 'GROUP_CONCAT',
    signature: 'GROUP_CONCAT(expr [SEPARATOR sep])',
    description: '拼接分组内的值，默认逗号分隔。',
    category: 'aggregate',
    insertText: "GROUP_CONCAT(${1:column} SEPARATOR ${2:','})",
  },
  {
    name: 'BIT_AND',
    signature: 'BIT_AND(expr)',
    description: '按位与聚合。',
    category: 'aggregate',
    insertText: 'BIT_AND(${1:column})',
  },
  {
    name: 'BIT_OR',
    signature: 'BIT_OR(expr)',
    description: '按位或聚合。',
    category: 'aggregate',
    insertText: 'BIT_OR(${1:column})',
  },
  {
    name: 'STDDEV',
    signature: 'STDDEV(expr)',
    description: '样本标准差。',
    category: 'aggregate',
    insertText: 'STDDEV(${1:column})',
  },
  {
    name: 'VARIANCE',
    signature: 'VARIANCE(expr)',
    description: '样本方差。',
    category: 'aggregate',
    insertText: 'VARIANCE(${1:column})',
  },

  // ===== 字符串函数 =====
  {
    name: 'CONCAT',
    signature: 'CONCAT(str1, str2, ...)',
    description: '拼接字符串，任一参数为 NULL 则返回 NULL。',
    category: 'string',
    insertText: 'CONCAT(${1:str1}, ${2:str2})',
  },
  {
    name: 'CONCAT_WS',
    signature: 'CONCAT_WS(separator, str1, str2, ...)',
    description: '用分隔符拼接，跳过 NULL。',
    category: 'string',
    insertText: "CONCAT_WS(${1:'-'}, ${2:str1}, ${3:str2})",
  },
  {
    name: 'SUBSTRING',
    signature: 'SUBSTRING(str, pos [, len])',
    description: '截取子串，位置从 1 开始。',
    category: 'string',
    insertText: 'SUBSTRING(${1:str}, ${2:1}, ${3:10})',
  },
  {
    name: 'SUBSTR',
    signature: 'SUBSTR(str, pos [, len])',
    description: 'SUBSTRING 的别名。',
    category: 'string',
    insertText: 'SUBSTR(${1:str}, ${2:1}, ${3:10})',
  },
  {
    name: 'LENGTH',
    signature: 'LENGTH(str)',
    description: '返回字节数。',
    category: 'string',
    insertText: 'LENGTH(${1:str})',
  },
  {
    name: 'CHAR_LENGTH',
    signature: 'CHAR_LENGTH(str)',
    description: '返回字符数。',
    category: 'string',
    insertText: 'CHAR_LENGTH(${1:str})',
  },
  {
    name: 'TRIM',
    signature: 'TRIM([{BOTH|LEADING|TRAILING} [remstr] FROM] str)',
    description: '去除首尾字符，默认空格。',
    category: 'string',
    insertText: 'TRIM(${1:str})',
  },
  {
    name: 'LTRIM',
    signature: 'LTRIM(str)',
    description: '去除左端空格。',
    category: 'string',
    insertText: 'LTRIM(${1:str})',
  },
  {
    name: 'RTRIM',
    signature: 'RTRIM(str)',
    description: '去除右端空格。',
    category: 'string',
    insertText: 'RTRIM(${1:str})',
  },
  {
    name: 'UPPER',
    signature: 'UPPER(str)',
    description: '转大写。',
    category: 'string',
    insertText: 'UPPER(${1:str})',
  },
  {
    name: 'LOWER',
    signature: 'LOWER(str)',
    description: '转小写。',
    category: 'string',
    insertText: 'LOWER(${1:str})',
  },
  {
    name: 'REPLACE',
    signature: 'REPLACE(str, from_str, to_str)',
    description: '全部替换。',
    category: 'string',
    insertText: "REPLACE(${1:str}, ${2:'a'}, ${3:'b'})",
  },
  {
    name: 'LEFT',
    signature: 'LEFT(str, n)',
    description: '返回左端 n 个字符。',
    category: 'string',
    insertText: 'LEFT(${1:str}, ${2:5})',
  },
  {
    name: 'RIGHT',
    signature: 'RIGHT(str, n)',
    description: '返回右端 n 个字符。',
    category: 'string',
    insertText: 'RIGHT(${1:str}, ${2:5})',
  },
  {
    name: 'LOCATE',
    signature: 'LOCATE(substr, str [, pos])',
    description: '返回子串位置（从 1 开始），未找到返回 0。',
    category: 'string',
    insertText: "LOCATE(${1:'sub'}, ${2:str})",
  },
  {
    name: 'INSTR',
    signature: 'INSTR(str, substr)',
    description: '返回子串位置（参数顺序与 LOCATE 相反）。',
    category: 'string',
    insertText: "INSTR(${1:str}, ${2:'sub'})",
  },
  {
    name: 'REVERSE',
    signature: 'REVERSE(str)',
    description: '反转字符串。',
    category: 'string',
    insertText: 'REVERSE(${1:str})',
  },
  {
    name: 'REPEAT',
    signature: 'REPEAT(str, count)',
    description: '重复字符串。',
    category: 'string',
    insertText: 'REPEAT(${1:str}, ${2:3})',
  },
  {
    name: 'LPAD',
    signature: 'LPAD(str, len, padstr)',
    description: '左填充到指定长度。',
    category: 'string',
    insertText: "LPAD(${1:str}, ${2:10}, ${3:' '})",
  },
  {
    name: 'RPAD',
    signature: 'RPAD(str, len, padstr)',
    description: '右填充到指定长度。',
    category: 'string',
    insertText: "RPAD(${1:str}, ${2:10}, ${3:' '})",
  },
  {
    name: 'FORMAT',
    signature: 'FORMAT(X, D [, locale])',
    description: '格式化数字，D 为小数位。',
    category: 'string',
    insertText: 'FORMAT(${1:123456.789}, ${2:2})',
  },
  {
    name: 'SUBSTRING_INDEX',
    signature: 'SUBSTRING_INDEX(str, delim, count)',
    description: '按分隔符截取前 N 段。',
    category: 'string',
    insertText: "SUBSTRING_INDEX(${1:str}, ${2:'.'}, ${3:2})",
  },
  {
    name: 'FIELD',
    signature: 'FIELD(str, str1, str2, ...)',
    description: '返回 str 在列表中的位置。',
    category: 'string',
    insertText: "FIELD(${1:str}, ${2:'a'}, ${3:'b'})",
  },
  {
    name: 'INSERT',
    signature: 'INSERT(str, pos, len, newstr)',
    description: '在指定位置替换子串。',
    category: 'string',
    insertText: "INSERT(${1:str}, ${2:1}, ${3:2}, ${4:'xx'})",
  },
  {
    name: 'HEX',
    signature: 'HEX(str_or_num)',
    description: '返回十六进制字符串。',
    category: 'string',
    insertText: 'HEX(${1:val})',
  },
  {
    name: 'UNHEX',
    signature: 'UNHEX(str)',
    description: '十六进制字符串解码。',
    category: 'string',
    insertText: "UNHEX(${1:'4D7953514C'})",
  },
  {
    name: 'REGEXP_REPLACE',
    signature: 'REGEXP_REPLACE(str, pattern, replace)',
    description: '正则替换。',
    category: 'string',
    minVersion: '8',
    insertText: "REGEXP_REPLACE(${1:str}, ${2:'[0-9]+'}, ${3:'#'})",
  },
  {
    name: 'REGEXP_INSTR',
    signature: 'REGEXP_INSTR(str, pattern)',
    description: '返回正则匹配的起始位置。',
    category: 'string',
    minVersion: '8',
    insertText: "REGEXP_INSTR(${1:str}, ${2:'[0-9]+'})",
  },
  {
    name: 'REGEXP_SUBSTR',
    signature: 'REGEXP_SUBSTR(str, pattern)',
    description: '返回正则匹配的子串。',
    category: 'string',
    minVersion: '8',
    insertText: "REGEXP_SUBSTR(${1:str}, ${2:'[0-9]+'})",
  },

  // ===== 日期时间函数 =====
  {
    name: 'NOW',
    signature: 'NOW()',
    description: '当前日期时间（YYYY-MM-DD HH:MM:SS）。',
    category: 'datetime',
    insertText: 'NOW()',
  },
  {
    name: 'CURDATE',
    signature: 'CURDATE()',
    description: '当前日期。',
    category: 'datetime',
    insertText: 'CURDATE()',
  },
  {
    name: 'CURTIME',
    signature: 'CURTIME()',
    description: '当前时间。',
    category: 'datetime',
    insertText: 'CURTIME()',
  },
  {
    name: 'SYSDATE',
    signature: 'SYSDATE()',
    description: '执行时刻的时间（与 NOW 不同）。',
    category: 'datetime',
    insertText: 'SYSDATE()',
  },
  {
    name: 'UNIX_TIMESTAMP',
    signature: 'UNIX_TIMESTAMP([date])',
    description: '返回 Unix 时间戳（秒）。',
    category: 'datetime',
    insertText: 'UNIX_TIMESTAMP(${1:date})',
  },
  {
    name: 'FROM_UNIXTIME',
    signature: 'FROM_UNIXTIME(unix_ts [, format])',
    description: 'Unix 时间戳转日期。',
    category: 'datetime',
    insertText: 'FROM_UNIXTIME(${1:1700000000})',
  },
  {
    name: 'DATE_FORMAT',
    signature: 'DATE_FORMAT(date, format)',
    description: '按格式字符串格式化日期。',
    category: 'datetime',
    insertText: "DATE_FORMAT(${1:date}, ${2:'%Y-%m-%d'})",
  },
  {
    name: 'STR_TO_DATE',
    signature: 'STR_TO_DATE(str, format)',
    description: '字符串转日期。',
    category: 'datetime',
    insertText: "STR_TO_DATE(${1:'2024-01-01'}, ${2:'%Y-%m-%d'})",
  },
  {
    name: 'DATE',
    signature: 'DATE(expr)',
    description: '提取日期部分。',
    category: 'datetime',
    insertText: 'DATE(${1:expr})',
  },
  {
    name: 'TIME',
    signature: 'TIME(expr)',
    description: '提取时间部分。',
    category: 'datetime',
    insertText: 'TIME(${1:expr})',
  },
  {
    name: 'YEAR',
    signature: 'YEAR(date)',
    description: '提取年份。',
    category: 'datetime',
    insertText: 'YEAR(${1:date})',
  },
  {
    name: 'MONTH',
    signature: 'MONTH(date)',
    description: '提取月份（1-12）。',
    category: 'datetime',
    insertText: 'MONTH(${1:date})',
  },
  {
    name: 'DAY',
    signature: 'DAY(date)',
    description: '提取日（1-31）。',
    category: 'datetime',
    insertText: 'DAY(${1:date})',
  },
  {
    name: 'HOUR',
    signature: 'HOUR(time)',
    description: '提取小时。',
    category: 'datetime',
    insertText: 'HOUR(${1:time})',
  },
  {
    name: 'MINUTE',
    signature: 'MINUTE(time)',
    description: '提取分钟。',
    category: 'datetime',
    insertText: 'MINUTE(${1:time})',
  },
  {
    name: 'SECOND',
    signature: 'SECOND(time)',
    description: '提取秒。',
    category: 'datetime',
    insertText: 'SECOND(${1:time})',
  },
  {
    name: 'DATE_ADD',
    signature: 'DATE_ADD(date, INTERVAL expr unit)',
    description: '日期加间隔。',
    category: 'datetime',
    insertText: "DATE_ADD(${1:date}, INTERVAL ${2:1} ${3:DAY})",
  },
  {
    name: 'DATE_SUB',
    signature: 'DATE_SUB(date, INTERVAL expr unit)',
    description: '日期减间隔。',
    category: 'datetime',
    insertText: "DATE_SUB(${1:date}, INTERVAL ${2:1} ${3:DAY})",
  },
  {
    name: 'DATEDIFF',
    signature: 'DATEDIFF(expr1, expr2)',
    description: '两个日期相差天数。',
    category: 'datetime',
    insertText: 'DATEDIFF(${1:date1}, ${2:date2})',
  },
  {
    name: 'TIMESTAMPDIFF',
    signature: 'TIMESTAMPDIFF(unit, expr1, expr2)',
    description: '两个时间差（指定单位）。',
    category: 'datetime',
    insertText: "TIMESTAMPDIFF(${1:SECOND}, ${2:t1}, ${3:t2})",
  },
  {
    name: 'LAST_DAY',
    signature: 'LAST_DAY(date)',
    description: '当月最后一天。',
    category: 'datetime',
    insertText: 'LAST_DAY(${1:date})',
  },

  // ===== 数值函数 =====
  {
    name: 'ROUND',
    signature: 'ROUND(X [, D])',
    description: '四舍五入到 D 位小数。',
    category: 'numeric',
    insertText: 'ROUND(${1:val}, ${2:2})',
  },
  {
    name: 'CEIL',
    signature: 'CEIL(X)',
    description: '向上取整。',
    category: 'numeric',
    insertText: 'CEIL(${1:val})',
  },
  {
    name: 'FLOOR',
    signature: 'FLOOR(X)',
    description: '向下取整。',
    category: 'numeric',
    insertText: 'FLOOR(${1:val})',
  },
  {
    name: 'TRUNCATE',
    signature: 'TRUNCATE(X, D)',
    description: '截断到 D 位小数。',
    category: 'numeric',
    insertText: 'TRUNCATE(${1:val}, ${2:2})',
  },
  {
    name: 'ABS',
    signature: 'ABS(X)',
    description: '绝对值。',
    category: 'numeric',
    insertText: 'ABS(${1:val})',
  },
  {
    name: 'POW',
    signature: 'POW(X, Y)',
    description: 'X 的 Y 次方。',
    category: 'numeric',
    insertText: 'POW(${1:x}, ${2:y})',
  },
  {
    name: 'SQRT',
    signature: 'SQRT(X)',
    description: '平方根。',
    category: 'numeric',
    insertText: 'SQRT(${1:val})',
  },
  {
    name: 'MOD',
    signature: 'MOD(N, M)',
    description: '取余。',
    category: 'numeric',
    insertText: 'MOD(${1:n}, ${2:m})',
  },
  {
    name: 'RAND',
    signature: 'RAND([seed])',
    description: '返回 0~1 随机数。',
    category: 'numeric',
    insertText: 'RAND()',
  },
  {
    name: 'GREATEST',
    signature: 'GREATEST(v1, v2, ...)',
    description: '返回最大值。',
    category: 'numeric',
    insertText: 'GREATEST(${1:v1}, ${2:v2})',
  },
  {
    name: 'LEAST',
    signature: 'LEAST(v1, v2, ...)',
    description: '返回最小值。',
    category: 'numeric',
    insertText: 'LEAST(${1:v1}, ${2:v2})',
  },
  {
    name: 'CONV',
    signature: 'CONV(N, from_base, to_base)',
    description: '进制转换。',
    category: 'numeric',
    insertText: 'CONV(${1:255}, ${2:10}, ${3:16})',
  },

  // ===== 窗口函数（MySQL 8+）=====
  {
    name: 'ROW_NUMBER',
    signature: 'ROW_NUMBER() OVER (...)',
    description: '行号。',
    category: 'window',
    minVersion: '8',
    insertText: 'ROW_NUMBER() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'RANK',
    signature: 'RANK() OVER (...)',
    description: '排名，跳号。',
    category: 'window',
    minVersion: '8',
    insertText: 'RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'DENSE_RANK',
    signature: 'DENSE_RANK() OVER (...)',
    description: '密集排名，不跳号。',
    category: 'window',
    minVersion: '8',
    insertText: 'DENSE_RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'LAG',
    signature: 'LAG(expr [, offset [, default]]) OVER (...)',
    description: '前 N 行的值。',
    category: 'window',
    minVersion: '8',
    insertText: 'LAG(${1:col}, ${2:1}) OVER (${3:PARTITION BY ${4:grp} ORDER BY ${5:ord}})',
  },
  {
    name: 'LEAD',
    signature: 'LEAD(expr [, offset [, default]]) OVER (...)',
    description: '后 N 行的值。',
    category: 'window',
    minVersion: '8',
    insertText: 'LEAD(${1:col}, ${2:1}) OVER (${3:PARTITION BY ${4:grp} ORDER BY ${5:ord}})',
  },
  {
    name: 'FIRST_VALUE',
    signature: 'FIRST_VALUE(expr) OVER (...)',
    description: '窗口第一个值。',
    category: 'window',
    minVersion: '8',
    insertText: 'FIRST_VALUE(${1:col}) OVER (${2:ORDER BY ${3:ord}})',
  },
  {
    name: 'LAST_VALUE',
    signature: 'LAST_VALUE(expr) OVER (...)',
    description: '窗口最后一个值。',
    category: 'window',
    minVersion: '8',
    insertText: 'LAST_VALUE(${1:col}) OVER (${2:ORDER BY ${3:ord} ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING})',
  },
  {
    name: 'NTILE',
    signature: 'NTILE(N) OVER (...)',
    description: '分桶。',
    category: 'window',
    minVersion: '8',
    insertText: 'NTILE(${1:4}) OVER (${2:ORDER BY ${3:col}})',
  },
  {
    name: 'PERCENT_RANK',
    signature: 'PERCENT_RANK() OVER (...)',
    description: '百分比排名。',
    category: 'window',
    minVersion: '8',
    insertText: 'PERCENT_RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'CUME_DIST',
    signature: 'CUME_DIST() OVER (...)',
    description: '累积分布。',
    category: 'window',
    minVersion: '8',
    insertText: 'CUME_DIST() OVER (${1:ORDER BY ${2:col}})',
  },

  // ===== 转换函数 =====
  {
    name: 'CAST',
    signature: 'CAST(expr AS type)',
    description: '类型转换。',
    category: 'conversion',
    insertText: 'CAST(${1:val} AS ${2:SIGNED})',
  },
  {
    name: 'CONVERT',
    signature: 'CONVERT(expr, type)',
    description: '类型转换（另一种语法）。',
    category: 'conversion',
    insertText: 'CONVERT(${1:val}, ${2:SIGNED})',
  },

  // ===== JSON 函数（MySQL 5.7+/8+）=====
  {
    name: 'JSON_EXTRACT',
    signature: 'JSON_EXTRACT(json, path...)',
    description: '按 JSONPath 提取值。',
    category: 'json',
    insertText: "JSON_EXTRACT(${1:json}, ${2:'$.key'})",
  },
  {
    name: 'JSON_UNQUOTE',
    signature: 'JSON_UNQUOTE(json)',
    description: '去除 JSON 引号。',
    category: 'json',
    insertText: 'JSON_UNQUOTE(${1:json})',
  },
  {
    name: 'JSON_OBJECT',
    signature: 'JSON_OBJECT(key, val...)',
    description: '构造 JSON 对象。',
    category: 'json',
    insertText: "JSON_OBJECT(${1:'key'}, ${2:value})",
  },
  {
    name: 'JSON_ARRAY',
    signature: 'JSON_ARRAY(val...)',
    description: '构造 JSON 数组。',
    category: 'json',
    insertText: 'JSON_ARRAY(${1:1}, ${2:2})',
  },
  {
    name: 'JSON_CONTAINS',
    signature: 'JSON_CONTAINS(target, candidate [, path])',
    description: '判断是否包含。',
    category: 'json',
    insertText: "JSON_CONTAINS(${1:json}, ${2:'\"val\"'})",
  },
  {
    name: 'JSON_LENGTH',
    signature: 'JSON_LENGTH(json)',
    description: 'JSON 长度。',
    category: 'json',
    insertText: 'JSON_LENGTH(${1:json})',
  },
  {
    name: 'JSON_KEYS',
    signature: 'JSON_KEYS(json)',
    description: '返回 JSON 对象的键数组。',
    category: 'json',
    insertText: 'JSON_KEYS(${1:json})',
  },
  {
    name: 'JSON_SET',
    signature: 'JSON_SET(json, path, val...)',
    description: '设置 JSON 路径值。',
    category: 'json',
    insertText: "JSON_SET(${1:json}, ${2:'$.key'}, ${3:value})",
  },
  {
    name: 'JSON_ARRAYAGG',
    signature: 'JSON_ARRAYAGG(expr)',
    description: '聚合为 JSON 数组。',
    category: 'json',
    minVersion: '8',
    insertText: 'JSON_ARRAYAGG(${1:col})',
  },
  {
    name: 'JSON_OBJECTAGG',
    signature: 'JSON_OBJECTAGG(key, val)',
    description: '聚合为 JSON 对象。',
    category: 'json',
    minVersion: '8',
    insertText: 'JSON_OBJECTAGG(${1:key}, ${2:val})',
  },
  {
    name: 'JSON_TABLE',
    signature: 'JSON_TABLE(json, path COLUMNS(...))',
    description: '从 JSON 提取为关系表。',
    category: 'json',
    minVersion: '8',
    insertText: "JSON_TABLE(${1:json}, ${2:'$[*]'} COLUMNS (${3:val VARCHAR(100) PATH '$.val'}))",
  },

  // ===== 系统函数 =====
  {
    name: 'VERSION',
    signature: 'VERSION()',
    description: 'MySQL 版本号。',
    category: 'system',
    insertText: 'VERSION()',
  },
  {
    name: 'DATABASE',
    signature: 'DATABASE()',
    description: '当前数据库名。',
    category: 'system',
    insertText: 'DATABASE()',
  },
  {
    name: 'USER',
    signature: 'USER()',
    description: '当前用户（user@host）。',
    category: 'system',
    insertText: 'USER()',
  },
  {
    name: 'CONNECTION_ID',
    signature: 'CONNECTION_ID()',
    description: '当前连接 ID。',
    category: 'system',
    insertText: 'CONNECTION_ID()',
  },
  {
    name: 'LAST_INSERT_ID',
    signature: 'LAST_INSERT_ID()',
    description: '最近一次自增 ID。',
    category: 'system',
    insertText: 'LAST_INSERT_ID()',
  },
  {
    name: 'UUID',
    signature: 'UUID()',
    description: '生成 UUID。',
    category: 'system',
    insertText: 'UUID()',
  },
  {
    name: 'SLEEP',
    signature: 'SLEEP(seconds)',
    description: '休眠指定秒数。',
    category: 'system',
    insertText: 'SLEEP(${1:1})',
  },

  // ===== 流程控制函数 =====
  {
    name: 'IF',
    signature: 'IF(cond, true_val, false_val)',
    description: '条件表达式。',
    category: 'conversion',
    insertText: 'IF(${1:cond}, ${2:true_val}, ${3:false_val})',
  },
  {
    name: 'IFNULL',
    signature: 'IFNULL(expr1, expr2)',
    description: 'expr1 为 NULL 则返回 expr2。',
    category: 'conversion',
    insertText: 'IFNULL(${1:val}, ${2:0})',
  },
  {
    name: 'NULLIF',
    signature: 'NULLIF(expr1, expr2)',
    description: '两值相等返回 NULL。',
    category: 'conversion',
    insertText: 'NULLIF(${1:v1}, ${2:v2})',
  },
  {
    name: 'COALESCE',
    signature: 'COALESCE(val1, val2, ...)',
    description: '返回第一个非 NULL 值。',
    category: 'conversion',
    insertText: 'COALESCE(${1:val1}, ${2:val2})',
  },
]
