import type { FunctionDef } from './types'

/**
 * PostgreSQL 内置函数清单。
 * minVersion 为主版本号，如 "13" 表示 PostgreSQL 13+ 可用。
 * 参考：https://www.postgresql.org/docs/manuals/
 */
export const POSTGRES_FUNCTIONS: FunctionDef[] = [
  // ===== 聚合函数 =====
  {
    name: 'COUNT',
    signature: 'COUNT(expression)',
    description: '统计行数。COUNT(*) 统计所有行，COUNT(col) 忽略 NULL。',
    category: 'aggregate',
    insertText: 'COUNT(${1:*})',
  },
  {
    name: 'SUM',
    signature: 'SUM(expression)',
    description: '求和，忽略 NULL。',
    category: 'aggregate',
    insertText: 'SUM(${1:column})',
  },
  {
    name: 'AVG',
    signature: 'AVG(expression)',
    description: '计算平均值，忽略 NULL。',
    category: 'aggregate',
    insertText: 'AVG(${1:column})',
  },
  {
    name: 'MIN',
    signature: 'MIN(expression)',
    description: '求最小值，忽略 NULL。',
    category: 'aggregate',
    insertText: 'MIN(${1:column})',
  },
  {
    name: 'MAX',
    signature: 'MAX(expression)',
    description: '求最大值，忽略 NULL。',
    category: 'aggregate',
    insertText: 'MAX(${1:column})',
  },
  {
    name: 'STRING_AGG',
    signature: 'STRING_AGG(expression, delimiter)',
    description: '将字符串拼接，用指定分隔符分隔。',
    category: 'aggregate',
    insertText: "STRING_AGG(${1:column}, ${2:', '})",
  },
  {
    name: 'ARRAY_AGG',
    signature: 'ARRAY_AGG(expression)',
    description: '将值聚合为数组。',
    category: 'aggregate',
    insertText: 'ARRAY_AGG(${1:column})',
  },
  {
    name: 'BOOL_OR',
    signature: 'BOOL_OR(expression)',
    description: '任一值为 TRUE 则返回 TRUE。',
    category: 'aggregate',
    insertText: 'BOOL_OR(${1:condition})',
  },
  {
    name: 'BOOL_AND',
    signature: 'BOOL_AND(expression)',
    description: '所有值为 TRUE 才返回 TRUE。',
    category: 'aggregate',
    insertText: 'BOOL_AND(${1:condition})',
  },

  // ===== 字符串函数 =====
  {
    name: 'COALESCE',
    signature: 'COALESCE(val1, val2, ...)',
    description: '返回第一个非 NULL 的参数值。',
    category: 'string',
    insertText: 'COALESCE(${1:val1}, ${2:val2})',
  },
  {
    name: 'NULLIF',
    signature: 'NULLIF(val1, val2)',
    description: '两值相等返回 NULL，否则返回 val1。',
    category: 'string',
    insertText: 'NULLIF(${1:val1}, ${2:val2})',
  },
  {
    name: 'CONCAT',
    signature: 'CONCAT(str1, str2, ...)',
    description: '拼接字符串，NULL 视为空串。',
    category: 'string',
    insertText: 'CONCAT(${1:str1}, ${2:str2})',
  },
  {
    name: 'CONCAT_WS',
    signature: 'CONCAT_WS(separator, str1, str2, ...)',
    description: '用分隔符拼接字符串，跳过 NULL。',
    category: 'string',
    insertText: "CONCAT_WS(${1:'-'}, ${2:str1}, ${3:str2})",
  },
  {
    name: 'SUBSTRING',
    signature: 'SUBSTRING(str FROM start [FOR length])',
    description: '截取子串。',
    category: 'string',
    insertText: 'SUBSTRING(${1:str} FROM ${2:1} FOR ${3:10})',
  },
  {
    name: 'LENGTH',
    signature: 'LENGTH(string)',
    description: '返回字符数。',
    category: 'string',
    insertText: 'LENGTH(${1:str})',
  },
  {
    name: 'CHAR_LENGTH',
    signature: 'CHAR_LENGTH(string)',
    description: '返回字符数（同 LENGTH）。',
    category: 'string',
    insertText: 'CHAR_LENGTH(${1:str})',
  },
  {
    name: 'OCTET_LENGTH',
    signature: 'OCTET_LENGTH(string)',
    description: '返回字节数。',
    category: 'string',
    insertText: 'OCTET_LENGTH(${1:str})',
  },
  {
    name: 'TRIM',
    signature: 'TRIM([LEADING|TRAILING|BOTH] [chars] FROM str)',
    description: '去除首尾指定字符，默认去空格。',
    category: 'string',
    insertText: 'TRIM(${1:str})',
  },
  {
    name: 'BTRIM',
    signature: 'BTRIM(string [, chars])',
    description: '去除两端指定字符，默认空格。',
    category: 'string',
    insertText: 'BTRIM(${1:str})',
  },
  {
    name: 'LTRIM',
    signature: 'LTRIM(string [, chars])',
    description: '去除左端指定字符。',
    category: 'string',
    insertText: 'LTRIM(${1:str})',
  },
  {
    name: 'RTRIM',
    signature: 'RTRIM(string [, chars])',
    description: '去除右端指定字符。',
    category: 'string',
    insertText: 'RTRIM(${1:str})',
  },
  {
    name: 'UPPER',
    signature: 'UPPER(string)',
    description: '转大写。',
    category: 'string',
    insertText: 'UPPER(${1:str})',
  },
  {
    name: 'LOWER',
    signature: 'LOWER(string)',
    description: '转小写。',
    category: 'string',
    insertText: 'LOWER(${1:str})',
  },
  {
    name: 'INITCAP',
    signature: 'INITCAP(string)',
    description: '每个单词首字母大写。',
    category: 'string',
    insertText: 'INITCAP(${1:str})',
  },
  {
    name: 'REPLACE',
    signature: 'REPLACE(str, from, to)',
    description: '将 str 中 from 替换为 to。',
    category: 'string',
    insertText: "REPLACE(${1:str}, ${2:'a'}, ${3:'b'})",
  },
  {
    name: 'TRANSLATE',
    signature: 'TRANSLATE(str, from, to)',
    description: '按字符逐个替换。',
    category: 'string',
    insertText: "TRANSLATE(${1:str}, ${2:'abc'}, ${3:'xyz'})",
  },
  {
    name: 'POSITION',
    signature: 'POSITION(substr IN str)',
    description: '返回子串位置（从 1 开始），未找到返回 0。',
    category: 'string',
    insertText: "POSITION(${1:'sub'} IN ${2:str})",
  },
  {
    name: 'SPLIT_PART',
    signature: 'SPLIT_PART(str, delimiter, field)',
    description: '按分隔符分割后返回第 N 段。',
    category: 'string',
    insertText: "SPLIT_PART(${1:str}, ${2:'.'}, ${3:1})",
  },
  {
    name: 'LEFT',
    signature: 'LEFT(string, n)',
    description: '返回左端 n 个字符。',
    category: 'string',
    insertText: 'LEFT(${1:str}, ${2:5})',
  },
  {
    name: 'RIGHT',
    signature: 'RIGHT(string, n)',
    description: '返回右端 n 个字符。',
    category: 'string',
    insertText: 'RIGHT(${1:str}, ${2:5})',
  },
  {
    name: 'REPEAT',
    signature: 'REPEAT(string, n)',
    description: '重复字符串 n 次。',
    category: 'string',
    insertText: 'REPEAT(${1:str}, ${2:3})',
  },
  {
    name: 'REVERSE',
    signature: 'REVERSE(string)',
    description: '反转字符串。',
    category: 'string',
    insertText: 'REVERSE(${1:str})',
  },
  {
    name: 'LPAD',
    signature: 'LPAD(str, length [, fill])',
    description: '左填充到指定长度。',
    category: 'string',
    insertText: "LPAD(${1:str}, ${2:10}, ${3:' '})",
  },
  {
    name: 'RPAD',
    signature: 'RPAD(str, length [, fill])',
    description: '右填充到指定长度。',
    category: 'string',
    insertText: "RPAD(${1:str}, ${2:10}, ${3:' '})",
  },
  {
    name: 'FORMAT',
    signature: 'FORMAT(fmt, args...)',
    description: '类似 printf 的格式化。',
    category: 'string',
    insertText: "FORMAT(${1:'%s'}, ${2:val})",
  },
  {
    name: 'REGEXP_MATCH',
    signature: 'REGEXP_MATCH(str, pattern [, flags])',
    description: '返回第一个匹配的子串数组。',
    category: 'string',
    insertText: "REGEXP_MATCH(${1:str}, ${2:'[0-9]+'})",
  },
  {
    name: 'REGEXP_MATCHES',
    signature: 'REGEXP_MATCHES(str, pattern [, flags])',
    description: '返回所有匹配的数组集合。',
    category: 'string',
    insertText: "REGEXP_MATCHES(${1:str}, ${2:'[0-9]+'}, ${3:'g'})",
  },
  {
    name: 'REGEXP_REPLACE',
    signature: 'REGEXP_REPLACE(str, pattern, replacement [, flags])',
    description: '正则替换。',
    category: 'string',
    insertText: "REGEXP_REPLACE(${1:str}, ${2:'[0-9]+'}, ${3:'#'})",
  },
  {
    name: 'REGEXP_SPLIT_TO_ARRAY',
    signature: 'REGEXP_SPLIT_TO_ARRAY(str, pattern [, flags])',
    description: '正则分割为数组。',
    category: 'string',
    insertText: "REGEXP_SPLIT_TO_ARRAY(${1:str}, ${2:'\\s+'})",
  },
  {
    name: 'REGEXP_SPLIT_TO_TABLE',
    signature: 'REGEXP_SPLIT_TO_TABLE(str, pattern [, flags])',
    description: '正则分割为多行。',
    category: 'string',
    insertText: "REGEXP_SPLIT_TO_TABLE(${1:str}, ${2:'\\s+'})",
  },

  // ===== 日期时间函数 =====
  {
    name: 'NOW',
    signature: 'NOW()',
    description: '当前事务开始时间，等价于 TRANSACTION_TIMESTAMP。',
    category: 'datetime',
    insertText: 'NOW()',
  },
  {
    name: 'CURRENT_TIMESTAMP',
    signature: 'CURRENT_TIMESTAMP',
    description: '当前事务开始时间。',
    category: 'datetime',
    insertText: 'CURRENT_TIMESTAMP',
  },
  {
    name: 'CURRENT_DATE',
    signature: 'CURRENT_DATE',
    description: '当前日期。',
    category: 'datetime',
    insertText: 'CURRENT_DATE',
  },
  {
    name: 'CURRENT_TIME',
    signature: 'CURRENT_TIME',
    description: '当前时间。',
    category: 'datetime',
    insertText: 'CURRENT_TIME',
  },
  {
    name: 'CLOCK_TIMESTAMP',
    signature: 'CLOCK_TIMESTAMP()',
    description: '实时当前时间（每条语句执行时刻）。',
    category: 'datetime',
    insertText: 'CLOCK_TIMESTAMP()',
  },
  {
    name: 'STATEMENT_TIMESTAMP',
    signature: 'STATEMENT_TIMESTAMP()',
    description: '当前语句开始时间。',
    category: 'datetime',
    insertText: 'STATEMENT_TIMESTAMP()',
  },
  {
    name: 'TRANSACTION_TIMESTAMP',
    signature: 'TRANSACTION_TIMESTAMP()',
    description: '当前事务开始时间（同 NOW）。',
    category: 'datetime',
    insertText: 'TRANSACTION_TIMESTAMP()',
  },
  {
    name: 'EXTRACT',
    signature: 'EXTRACT(field FROM source)',
    description: '从日期/时间中提取字段（如 YEAR、MONTH、DAY、HOUR）。',
    category: 'datetime',
    insertText: 'EXTRACT(${1:YEAR} FROM ${2:timestamp})',
  },
  {
    name: 'DATE_PART',
    signature: 'DATE_PART(field, source)',
    description: '提取日期字段，等价于 EXTRACT。',
    category: 'datetime',
    insertText: "DATE_PART(${1:'year'}, ${2:timestamp})",
  },
  {
    name: 'DATE_TRUNC',
    signature: 'DATE_TRUNC(field, source [, time_zone])',
    description: '按字段截断日期，如按月截断。',
    category: 'datetime',
    insertText: "DATE_TRUNC(${1:'month'}, ${2:timestamp})",
  },
  {
    name: 'AGE',
    signature: 'AGE(timestamp [, end])',
    description: '计算时间差，返回 interval。',
    category: 'datetime',
    insertText: 'AGE(${1:timestamp1}, ${2:timestamp2})',
  },
  {
    name: 'JUSTIFY_INTERVAL',
    signature: 'JUSTIFY_INTERVAL(interval)',
    description: '调整 interval，使 24 小时进 1 天。',
    category: 'datetime',
    insertText: 'JUSTIFY_INTERVAL(${1:interval})',
  },
  {
    name: 'TO_CHAR',
    signature: 'TO_CHAR(value, format)',
    description: '格式化为字符串，支持日期/数值。',
    category: 'datetime',
    insertText: "TO_CHAR(${1:timestamp}, ${2:'YYYY-MM-DD'})",
  },
  {
    name: 'TO_DATE',
    signature: 'TO_DATE(str, format)',
    description: '字符串转日期。',
    category: 'datetime',
    insertText: "TO_DATE(${1:'2024-01-01'}, ${2:'YYYY-MM-DD'})",
  },
  {
    name: 'TO_TIMESTAMP',
    signature: 'TO_TIMESTAMP(str, format)',
    description: '字符串转时间戳。',
    category: 'datetime',
    insertText: "TO_TIMESTAMP(${1:'2024-01-01 00:00:00'}, ${2:'YYYY-MM-DD HH24:MI:SS'})",
  },
  {
    name: 'MAKE_DATE',
    signature: 'MAKE_DATE(year, month, day)',
    description: '构造日期。',
    category: 'datetime',
    insertText: 'MAKE_DATE(${1:2024}, ${2:1}, ${3:1})',
  },
  {
    name: 'MAKE_TIMESTAMP',
    signature: 'MAKE_TIMESTAMP(year, month, day, hour, min, sec)',
    description: '构造时间戳。',
    category: 'datetime',
    insertText: 'MAKE_TIMESTAMP(${1:2024}, ${2:1}, ${3:1}, ${4:0}, ${5:0}, ${6:0})',
  },

  // ===== 数值函数 =====
  {
    name: 'ROUND',
    signature: 'ROUND(numeric [, dp])',
    description: '四舍五入到指定小数位。',
    category: 'numeric',
    insertText: 'ROUND(${1:val}, ${2:2})',
  },
  {
    name: 'CEIL',
    signature: 'CEIL(numeric)',
    description: '向上取整。',
    category: 'numeric',
    insertText: 'CEIL(${1:val})',
  },
  {
    name: 'FLOOR',
    signature: 'FLOOR(numeric)',
    description: '向下取整。',
    category: 'numeric',
    insertText: 'FLOOR(${1:val})',
  },
  {
    name: 'TRUNC',
    signature: 'TRUNC(numeric [, dp])',
    description: '截断到指定小数位，不四舍五入。',
    category: 'numeric',
    insertText: 'TRUNC(${1:val}, ${2:0})',
  },
  {
    name: 'ABS',
    signature: 'ABS(numeric)',
    description: '绝对值。',
    category: 'numeric',
    insertText: 'ABS(${1:val})',
  },
  {
    name: 'POWER',
    signature: 'POWER(a, b)',
    description: 'a 的 b 次方。',
    category: 'numeric',
    insertText: 'POWER(${1:a}, ${2:b})',
  },
  {
    name: 'SQRT',
    signature: 'SQRT(numeric)',
    description: '平方根。',
    category: 'numeric',
    insertText: 'SQRT(${1:val})',
  },
  {
    name: 'MOD',
    signature: 'MOD(n, m)',
    description: '取余。',
    category: 'numeric',
    insertText: 'MOD(${1:n}, ${2:m})',
  },
  {
    name: 'RANDOM',
    signature: 'RANDOM()',
    description: '返回 0.0 到 1.0 之间的随机数。',
    category: 'numeric',
    insertText: 'RANDOM()',
  },
  {
    name: 'GREATEST',
    signature: 'GREATEST(val1, val2, ...)',
    description: '返回最大值。',
    category: 'numeric',
    insertText: 'GREATEST(${1:val1}, ${2:val2})',
  },
  {
    name: 'LEAST',
    signature: 'LEAST(val1, val2, ...)',
    description: '返回最小值。',
    category: 'numeric',
    insertText: 'LEAST(${1:val1}, ${2:val2})',
  },
  {
    name: 'WIDTH_BUCKET',
    signature: 'WIDTH_BUCKET(operand, b1, b2, count)',
    description: '返回操作数所属的桶编号。',
    category: 'numeric',
    insertText: 'WIDTH_BUCKET(${1:val}, ${2:0}, ${3:100}, ${4:10})',
  },

  // ===== JSON 函数 =====
  {
    name: 'JSON_EXTRACT_PATH',
    signature: 'JSON_EXTRACT_PATH(json, keys...)',
    description: '按路径提取 JSON 值。',
    category: 'json',
    insertText: "JSON_EXTRACT_PATH(${1:json}, ${2:'key'})",
  },
  {
    name: 'JSON_EXTRACT_PATH_TEXT',
    signature: 'JSON_EXTRACT_PATH_TEXT(json, keys...)',
    description: '按路径提取 JSON 值并返回文本。',
    category: 'json',
    insertText: "JSON_EXTRACT_PATH_TEXT(${1:json}, ${2:'key'})",
  },
  {
    name: 'JSON_OBJECT_KEYS',
    signature: 'JSON_OBJECT_KEYS(json)',
    description: '返回 JSON 对象的键集合。',
    category: 'json',
    insertText: 'JSON_OBJECT_KEYS(${1:json})',
  },
  {
    name: 'JSON_ARRAY_ELEMENTS',
    signature: 'JSON_ARRAY_ELEMENTS(json)',
    description: '将 JSON 数组展开为行集。',
    category: 'json',
    insertText: 'JSON_ARRAY_ELEMENTS(${1:json})',
  },
  {
    name: 'JSON_ARRAY_LENGTH',
    signature: 'JSON_ARRAY_LENGTH(json)',
    description: '返回 JSON 数组长度。',
    category: 'json',
    insertText: 'JSON_ARRAY_LENGTH(${1:json})',
  },
  {
    name: 'JSON_BUILD_OBJECT',
    signature: 'JSON_BUILD_OBJECT(keys, values...)',
    description: '构造 JSON 对象。',
    category: 'json',
    insertText: "JSON_BUILD_OBJECT(${1:'key'}, ${2:value})",
  },
  {
    name: 'JSON_AGG',
    signature: 'JSON_AGG(expression)',
    description: '聚合为 JSON 数组。',
    category: 'json',
    insertText: 'JSON_AGG(${1:row})',
  },
  {
    name: 'JSONB_BUILD_OBJECT',
    signature: 'JSONB_BUILD_OBJECT(keys, values...)',
    description: '构造 jsonb 对象。',
    category: 'json',
    insertText: "JSONB_BUILD_OBJECT(${1:'key'}, ${2:value})",
  },
  {
    name: 'JSONB_AGG',
    signature: 'JSONB_AGG(expression)',
    description: '聚合为 jsonb 数组。',
    category: 'json',
    insertText: 'JSONB_AGG(${1:row})',
  },
  {
    name: 'TO_JSON',
    signature: 'TO_JSON(value)',
    description: '将值转为 JSON。',
    category: 'json',
    insertText: 'TO_JSON(${1:val})',
  },
  {
    name: 'TO_JSONB',
    signature: 'TO_JSONB(value)',
    description: '将值转为 jsonb。',
    category: 'json',
    insertText: 'TO_JSONB(${1:val})',
  },
  {
    name: 'JSONB_SET',
    signature: 'JSONB_SET(target, path, new_value [, create])',
    description: '设置 jsonb 中指定路径的值。',
    category: 'json',
    insertText: "JSONB_SET(${1:target}, ${2:'{key}'}, ${3:'\"new\"'})",
  },
  {
    name: 'JSONB_PRETTY',
    signature: 'JSONB_PRETTY(jsonb)',
    description: '美化输出 jsonb。',
    category: 'json',
    insertText: 'JSONB_PRETTY(${1:jsonb})',
  },

  // ===== 窗口函数 =====
  {
    name: 'ROW_NUMBER',
    signature: 'ROW_NUMBER() OVER (ORDER BY ...)',
    description: '行号，从 1 开始。',
    category: 'window',
    insertText: 'ROW_NUMBER() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'RANK',
    signature: 'RANK() OVER (ORDER BY ...)',
    description: '排名，相同值同排名且会跳号。',
    category: 'window',
    insertText: 'RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'DENSE_RANK',
    signature: 'DENSE_RANK() OVER (ORDER BY ...)',
    description: '密集排名，相同值同排名且不跳号。',
    category: 'window',
    insertText: 'DENSE_RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'LAG',
    signature: 'LAG(value [, offset [, default]]) OVER (...',
    description: '取当前行之前第 N 行的值。',
    category: 'window',
    insertText: 'LAG(${1:col}, ${2:1}) OVER (${3:PARTITION BY ${4:grp} ORDER BY ${5:ord}})',
  },
  {
    name: 'LEAD',
    signature: 'LEAD(value [, offset [, default]]) OVER (...',
    description: '取当前行之后第 N 行的值。',
    category: 'window',
    insertText: 'LEAD(${1:col}, ${2:1}) OVER (${3:PARTITION BY ${4:grp} ORDER BY ${5:ord}})',
  },
  {
    name: 'FIRST_VALUE',
    signature: 'FIRST_VALUE(value) OVER (...',
    description: '窗口内第一个值。',
    category: 'window',
    insertText: 'FIRST_VALUE(${1:col}) OVER (${2:ORDER BY ${3:ord}})',
  },
  {
    name: 'LAST_VALUE',
    signature: 'LAST_VALUE(value) OVER (...',
    description: '窗口内最后一个值（注意窗口范围）。',
    category: 'window',
    insertText: 'LAST_VALUE(${1:col}) OVER (${2:ORDER BY ${3:ord} ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING})',
  },
  {
    name: 'NTILE',
    signature: 'NTILE(n) OVER (...',
    description: '将行分为 n 桶，返回桶号。',
    category: 'window',
    insertText: 'NTILE(${1:4}) OVER (${2:ORDER BY ${3:col}})',
  },
  {
    name: 'PERCENT_RANK',
    signature: 'PERCENT_RANK() OVER (...',
    description: '百分比排名（0~1）。',
    category: 'window',
    insertText: 'PERCENT_RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'CUME_DIST',
    signature: 'CUME_DIST() OVER (...',
    description: '累积分布。',
    category: 'window',
    insertText: 'CUME_DIST() OVER (${1:ORDER BY ${2:col}})',
  },

  // ===== 数组函数 =====
  {
    name: 'ARRAY_LENGTH',
    signature: 'ARRAY_LENGTH(array, dim)',
    description: '返回指定维度的长度。',
    category: 'array',
    insertText: 'ARRAY_LENGTH(${1:arr}, ${2:1})',
  },
  {
    name: 'ARRAY_APPEND',
    signature: 'ARRAY_APPEND(array, element)',
    description: '向数组末尾追加元素。',
    category: 'array',
    insertText: 'ARRAY_APPEND(${1:arr}, ${2:elem})',
  },
  {
    name: 'ARRAY_PREPEND',
    signature: 'ARRAY_PREPEND(element, array)',
    description: '向数组头部插入元素。',
    category: 'array',
    insertText: 'ARRAY_PREPEND(${1:elem}, ${2:arr})',
  },
  {
    name: 'ARRAY_CAT',
    signature: 'ARRAY_CAT(array1, array2)',
    description: '连接两个数组。',
    category: 'array',
    insertText: 'ARRAY_CAT(${1:arr1}, ${2:arr2})',
  },
  {
    name: 'ARRAY_TO_STRING',
    signature: 'ARRAY_TO_STRING(array, delimiter [, null_str])',
    description: '数组转字符串。',
    category: 'array',
    insertText: "ARRAY_TO_STRING(${1:arr}, ${2:', '})",
  },
  {
    name: 'STRING_TO_ARRAY',
    signature: 'STRING_TO_ARRAY(str, delimiter [, null_str])',
    description: '字符串转数组。',
    category: 'array',
    insertText: "STRING_TO_ARRAY(${1:str}, ${2:','})",
  },
  {
    name: 'UNNEST',
    signature: 'UNNEST(array)',
    description: '将数组展开为行集。',
    category: 'array',
    insertText: 'UNNEST(${1:arr})',
  },
  {
    name: 'ARRAY_POSITION',
    signature: 'ARRAY_POSITION(array, element)',
    description: '返回元素在数组中的位置。',
    category: 'array',
    insertText: 'ARRAY_POSITION(${1:arr}, ${2:elem})',
  },

  // ===== 转换函数 =====
  {
    name: 'CAST',
    signature: 'CAST(value AS type)',
    description: '类型转换。',
    category: 'conversion',
    insertText: 'CAST(${1:val} AS ${2:integer})',
  },
  {
    name: 'TO_NUMBER',
    signature: 'TO_NUMBER(str, format)',
    description: '字符串转数值。',
    category: 'conversion',
    insertText: "TO_NUMBER(${1:'123'}, ${2:'999'})",
  },
  {
    name: 'ENCODE',
    signature: 'ENCODE(data, format)',
    description: '二进制转文本编码（base64/hex）。',
    category: 'conversion',
    insertText: "ENCODE(${1:data}, ${2:'base64'})",
  },
  {
    name: 'DECODE',
    signature: 'DECODE(text, format)',
    description: '文本解码为二进制。',
    category: 'conversion',
    insertText: "DECODE(${1:text}, ${2:'base64'})",
  },

  // ===== 系统函数 =====
  {
    name: 'GENERATE_SERIES',
    signature: 'GENERATE_SERIES(start, stop [, step])',
    description: '生成序列。',
    category: 'system',
    insertText: 'GENERATE_SERIES(${1:1}, ${2:10})',
  },
  {
    name: 'VERSION',
    signature: 'VERSION()',
    description: '返回 PostgreSQL 版本字符串。',
    category: 'system',
    insertText: 'VERSION()',
  },
  {
    name: 'CURRENT_USER',
    signature: 'CURRENT_USER',
    description: '当前用户名。',
    category: 'system',
    insertText: 'CURRENT_USER',
  },
  {
    name: 'CURRENT_DATABASE',
    signature: 'CURRENT_DATABASE()',
    description: '当前数据库名。',
    category: 'system',
    insertText: 'CURRENT_DATABASE()',
  },
  {
    name: 'CURRENT_SCHEMA',
    signature: 'CURRENT_SCHEMA()',
    description: '当前 schema 名。',
    category: 'system',
    insertText: 'CURRENT_SCHEMA()',
  },
  {
    name: 'PG_GET_USERBYID',
    signature: 'PG_GET_USERBYID(oid)',
    description: '按 OID 查用户名。',
    category: 'system',
    insertText: 'PG_GET_USERBYID(${1:oid})',
  },

  // ===== PG 13+ 新增 =====
  {
    name: 'JSONB_PATH_QUERY',
    signature: 'JSONB_PATH_QUERY(jsonb, path)',
    description: '按 JSONPath 查询，返回匹配集合。',
    category: 'json',
    minVersion: '12',
    insertText: "JSONB_PATH_QUERY(${1:jsonb}, ${2:'$.key'})",
  },
  {
    name: 'JSONB_PATH_EXISTS',
    signature: 'JSONB_PATH_EXISTS(jsonb, path)',
    description: '判断 JSONPath 是否有匹配。',
    category: 'json',
    minVersion: '12',
    insertText: "JSONB_PATH_EXISTS(${1:jsonb}, ${2:'$.key'})",
  },
  {
    name: 'MIN_SCALE',
    signature: 'MIN_SCALE(numeric)',
    description: '返回数值的最小标度。',
    category: 'numeric',
    minVersion: '13',
    insertText: 'MIN_SCALE(${1:val})',
  },
  {
    name: 'NORMALIZE',
    signature: 'NORMALIZE(text [, form])',
    description: 'Unicode 规范化。',
    category: 'string',
    minVersion: '13',
    insertText: 'NORMALIZE(${1:str})',
  },

  // ===== PG 14+ 新增 =====
  {
    name: 'DATE_BIN',
    signature: 'DATE_BIN(stride, source, origin)',
    description: '按固定间隔对齐时间。',
    category: 'datetime',
    minVersion: '14',
    insertText: "DATE_BIN(${1:interval '15 minutes'}, ${2:ts}, ${3:timestamp '2000-01-01'})",
  },

  // ===== PG 16+ 新增 =====
  {
    name: 'ARRAY_SHUFFLE',
    signature: 'ARRAY_SHUFFLE(array)',
    description: '随机打乱数组顺序。',
    category: 'array',
    minVersion: '16',
    insertText: 'ARRAY_SHUFFLE(${1:arr})',
  },
]
