import type { FunctionDef } from './types'

/**
 * SQLite 内置函数清单。
 * SQLite 函数集相对精简，版本差异通过 minVersion 标注。
 * 参考：https://www.sqlite.org/lang_corefunc.html
 */
export const SQLITE_FUNCTIONS: FunctionDef[] = [
  // ===== 聚合函数 =====
  {
    name: 'COUNT',
    signature: 'COUNT(expr)',
    description: '统计行数。COUNT(*) 含所有行。',
    category: 'aggregate',
    insertText: 'COUNT(${1:*})',
  },
  {
    name: 'SUM',
    signature: 'SUM(expr)',
    description: '求和，忽略 NULL。',
    category: 'aggregate',
    insertText: 'SUM(${1:column})',
  },
  {
    name: 'TOTAL',
    signature: 'TOTAL(expr)',
    description: '求和，返回浮点数，无行时为 0.0。',
    category: 'aggregate',
    insertText: 'TOTAL(${1:column})',
  },
  {
    name: 'AVG',
    signature: 'AVG(expr)',
    description: '平均值。',
    category: 'aggregate',
    insertText: 'AVG(${1:column})',
  },
  {
    name: 'MIN',
    signature: 'MIN(expr)',
    description: '最小值。',
    category: 'aggregate',
    insertText: 'MIN(${1:column})',
  },
  {
    name: 'MAX',
    signature: 'MAX(expr)',
    description: '最大值。',
    category: 'aggregate',
    insertText: 'MAX(${1:column})',
  },
  {
    name: 'GROUP_CONCAT',
    signature: 'GROUP_CONCAT(expr [, separator])',
    description: '拼接分组值，默认逗号分隔。',
    category: 'aggregate',
    insertText: "GROUP_CONCAT(${1:column}, ${2:','})",
  },

  // ===== 字符串函数 =====
  {
    name: 'LENGTH',
    signature: 'LENGTH(str)',
    description: '返回字符数（对 BLOB 返回字节数）。',
    category: 'string',
    insertText: 'LENGTH(${1:str})',
  },
  {
    name: 'LOWER',
    signature: 'LOWER(str)',
    description: '转小写。',
    category: 'string',
    insertText: 'LOWER(${1:str})',
  },
  {
    name: 'UPPER',
    signature: 'UPPER(str)',
    description: '转大写。',
    category: 'string',
    insertText: 'UPPER(${1:str})',
  },
  {
    name: 'TRIM',
    signature: 'TRIM(str [, chars])',
    description: '去除两端字符，默认空格。',
    category: 'string',
    insertText: 'TRIM(${1:str})',
  },
  {
    name: 'LTRIM',
    signature: 'LTRIM(str [, chars])',
    description: '去除左端字符。',
    category: 'string',
    insertText: 'LTRIM(${1:str})',
  },
  {
    name: 'RTRIM',
    signature: 'RTRIM(str [, chars])',
    description: '去除右端字符。',
    category: 'string',
    insertText: 'RTRIM(${1:str})',
  },
  {
    name: 'SUBSTR',
    signature: 'SUBSTR(str, start [, length])',
    description: '截取子串，位置从 1 开始，负数从末尾算。',
    category: 'string',
    insertText: 'SUBSTR(${1:str}, ${2:1}, ${3:10})',
  },
  {
    name: 'REPLACE',
    signature: 'REPLACE(str, from, to)',
    description: '全部替换。',
    category: 'string',
    insertText: "REPLACE(${1:str}, ${2:'a'}, ${3:'b'})",
  },
  {
    name: 'INSTR',
    signature: 'INSTR(str, substr)',
    description: '返回子串位置（从 1 开始），未找到返回 0。',
    category: 'string',
    insertText: "INSTR(${1:str}, ${2:'sub'})",
  },
  {
    name: 'PRINTF',
    signature: 'PRINTF(format, args...)',
    description: '格式化字符串（类似 printf）。',
    category: 'string',
    insertText: "PRINTF(${1:'%s'}, ${2:val})",
  },
  {
    name: 'QUOTE',
    signature: 'QUOTE(str)',
    description: '返回带引号的字面量。',
    category: 'string',
    insertText: 'QUOTE(${1:str})',
  },
  {
    name: 'HEX',
    signature: 'HEX(value)',
    description: '返回十六进制表示。',
    category: 'string',
    insertText: 'HEX(${1:val})',
  },
  {
    name: 'UNHEX',
    signature: 'UNHEX(hex_str)',
    description: '十六进制解码为 BLOB。',
    category: 'string',
    minVersion: '3',
    insertText: "UNHEX(${1:'48656C6C6F'})",
  },
  {
    name: 'CHAR',
    signature: 'CHAR(c1, c2, ...)',
    description: '按 Unicode 码点构造字符串。',
    category: 'string',
    insertText: 'CHAR(${1:72}, ${2:73})',
  },

  // ===== 日期时间函数 =====
  {
    name: 'DATE',
    signature: 'DATE(timestr [, modifiers...])',
    description: '返回 YYYY-MM-DD。',
    category: 'datetime',
    insertText: "DATE(${1:'now'})",
  },
  {
    name: 'TIME',
    signature: 'TIME(timestr [, modifiers...])',
    description: '返回 HH:MM:SS。',
    category: 'datetime',
    insertText: "TIME(${1:'now'})",
  },
  {
    name: 'DATETIME',
    signature: 'DATETIME(timestr [, modifiers...])',
    description: '返回 YYYY-MM-DD HH:MM:SS。',
    category: 'datetime',
    insertText: "DATETIME(${1:'now'})",
  },
  {
    name: 'JULIANDAY',
    signature: 'JULIANDAY(timestr [, modifiers...])',
    description: '儒略日（浮点数）。',
    category: 'datetime',
    insertText: "JULIANDAY(${1:'now'})",
  },
  {
    name: 'STRFTIME',
    signature: 'STRFTIME(format, timestr [, modifiers...])',
    description: '按格式化字符串输出日期。',
    category: 'datetime',
    insertText: "STRFTIME(${1:'%Y-%m-%d'}, ${2:'now'})",
  },
  {
    name: 'UNIXEPOCH',
    signature: 'UNIXEPOCH([timestr [, modifiers...]])',
    description: '返回 Unix 时间戳（秒）。',
    category: 'datetime',
    minVersion: '3',
    insertText: "UNIXEPOCH(${1:'now'})",
  },

  // ===== 数值函数 =====
  {
    name: 'ABS',
    signature: 'ABS(X)',
    description: '绝对值。',
    category: 'numeric',
    insertText: 'ABS(${1:val})',
  },
  {
    name: 'ROUND',
    signature: 'ROUND(X [, D])',
    description: '四舍五入到 D 位小数。',
    category: 'numeric',
    insertText: 'ROUND(${1:val}, ${2:2})',
  },
  {
    name: 'RANDOM',
    signature: 'RANDOM()',
    description: '返回 -2^63 到 2^63-1 的随机整数。',
    category: 'numeric',
    insertText: 'RANDOM()',
  },
  {
    name: 'RANDOMBLOB',
    signature: 'RANDOMBLOB(N)',
    description: '返回 N 字节随机 BLOB。',
    category: 'numeric',
    insertText: 'RANDOMBLOB(${1:16})',
  },
  {
    name: 'MAX',
    signature: 'MAX(val1, val2, ...)',
    description: '标量版：返回参数最大值。',
    category: 'numeric',
    insertText: 'MAX(${1:v1}, ${2:v2})',
  },
  {
    name: 'MIN',
    signature: 'MIN(val1, val2, ...)',
    description: '标量版：返回参数最小值。',
    category: 'numeric',
    insertText: 'MIN(${1:v1}, ${2:v2})',
  },

  // ===== 系统函数 =====
  {
    name: 'COALESCE',
    signature: 'COALESCE(val1, val2, ...)',
    description: '返回第一个非 NULL 值。',
    category: 'system',
    insertText: 'COALESCE(${1:val1}, ${2:val2})',
  },
  {
    name: 'NULLIF',
    signature: 'NULLIF(val1, val2)',
    description: '两值相等返回 NULL。',
    category: 'system',
    insertText: 'NULLIF(${1:v1}, ${2:v2})',
  },
  {
    name: 'IIF',
    signature: 'IIF(cond, true_val, false_val)',
    description: '内联条件表达式。',
    category: 'system',
    minVersion: '3',
    insertText: 'IIF(${1:cond}, ${2:t}, ${3:f})',
  },
  {
    name: 'TYPEOF',
    signature: 'TYPEOF(expr)',
    description: '返回表达式类型（null/integer/real/text/blob）。',
    category: 'system',
    insertText: 'TYPEOF(${1:val})',
  },
  {
    name: 'LAST_INSERT_ROWID',
    signature: 'LAST_INSERT_ROWID()',
    description: '当前连接最近插入的 rowid。',
    category: 'system',
    insertText: 'LAST_INSERT_ROWID()',
  },
  {
    name: 'SQLITE_VERSION',
    signature: 'SQLITE_VERSION()',
    description: 'SQLite 版本号。',
    category: 'system',
    insertText: 'SQLITE_VERSION()',
  },
  {
    name: 'CHANGES',
    signature: 'CHANGES()',
    description: '最近一条语句影响的行数。',
    category: 'system',
    insertText: 'CHANGES()',
  },

  // ===== 窗口函数（SQLite 3.25+）=====
  {
    name: 'ROW_NUMBER',
    signature: 'ROW_NUMBER() OVER (...)',
    description: '行号。',
    category: 'window',
    minVersion: '3',
    insertText: 'ROW_NUMBER() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'RANK',
    signature: 'RANK() OVER (...)',
    description: '排名，跳号。',
    category: 'window',
    minVersion: '3',
    insertText: 'RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'DENSE_RANK',
    signature: 'DENSE_RANK() OVER (...)',
    description: '密集排名。',
    category: 'window',
    minVersion: '3',
    insertText: 'DENSE_RANK() OVER (${1:ORDER BY ${2:col}})',
  },
  {
    name: 'LAG',
    signature: 'LAG(expr [, offset [, default]]) OVER (...)',
    description: '前 N 行的值。',
    category: 'window',
    minVersion: '3',
    insertText: 'LAG(${1:col}, ${2:1}) OVER (${3:PARTITION BY ${4:grp} ORDER BY ${5:ord}})',
  },
  {
    name: 'LEAD',
    signature: 'LEAD(expr [, offset [, default]]) OVER (...)',
    description: '后 N 行的值。',
    category: 'window',
    minVersion: '3',
    insertText: 'LEAD(${1:col}, ${2:1}) OVER (${3:PARTITION BY ${4:grp} ORDER BY ${5:ord}})',
  },
  {
    name: 'FIRST_VALUE',
    signature: 'FIRST_VALUE(expr) OVER (...)',
    description: '窗口第一个值。',
    category: 'window',
    minVersion: '3',
    insertText: 'FIRST_VALUE(${1:col}) OVER (${2:ORDER BY ${3:ord}})',
  },
  {
    name: 'LAST_VALUE',
    signature: 'LAST_VALUE(expr) OVER (...)',
    description: '窗口最后一个值。',
    category: 'window',
    minVersion: '3',
    insertText: 'LAST_VALUE(${1:col}) OVER (${2:ORDER BY ${3:ord} ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING})',
  },

  // ===== JSON 函数（SQLite 3.9+，编译时需启用 JSON1）=====
  {
    name: 'JSON_EXTRACT',
    signature: 'JSON_EXTRACT(json, path...)',
    description: '按 JSONPath 提取值。',
    category: 'json',
    minVersion: '3',
    insertText: "JSON_EXTRACT(${1:json}, ${2:'$.key'})",
  },
  {
    name: 'JSON_OBJECT',
    signature: 'JSON_OBJECT(key, val...)',
    description: '构造 JSON 对象。',
    category: 'json',
    minVersion: '3',
    insertText: "JSON_OBJECT(${1:'key'}, ${2:value})",
  },
  {
    name: 'JSON_ARRAY',
    signature: 'JSON_ARRAY(val...)',
    description: '构造 JSON 数组。',
    category: 'json',
    minVersion: '3',
    insertText: 'JSON_ARRAY(${1:1}, ${2:2})',
  },
  {
    name: 'JSON_TYPE',
    signature: 'JSON_TYPE(json [, path])',
    description: '返回 JSON 值类型。',
    category: 'json',
    minVersion: '3',
    insertText: 'JSON_TYPE(${1:json})',
  },
  {
    name: 'JSON_VALID',
    signature: 'JSON_VALID(str)',
    description: '判断是否为合法 JSON。',
    category: 'json',
    minVersion: '3',
    insertText: 'JSON_VALID(${1:str})',
  },
  {
    name: 'JSON_GROUP_ARRAY',
    signature: 'JSON_GROUP_OBJECT(key, value)',
    description: '聚合为 JSON 数组。',
    category: 'json',
    minVersion: '3',
    insertText: 'JSON_GROUP_ARRAY(${1:val})',
  },
  {
    name: 'JSON_GROUP_OBJECT',
    signature: 'JSON_GROUP_OBJECT(key, value)',
    description: '聚合为 JSON 对象。',
    category: 'json',
    minVersion: '3',
    insertText: 'JSON_GROUP_OBJECT(${1:key}, ${2:val})',
  },
]
